// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://ygxlplfdrpkxqszesmtn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlneGxwbGZkcnBreHFzemVzbXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMzAzNzAsImV4cCI6MjA5NDcwNjM3MH0.KegTqYTFxRoq7mpD7g5ymGESWEaqHiLGyWW2pkijN-8";

export const supabase = createClient<{ crm: Database['public'] }>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: { schema: 'crm' },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
